title: Eliud Njoki # your name (or website title) here
logo: "/images/tOzFCjx-cat-wallpapers.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | IT professional | Writer | Poet 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/eliud-nduati/">View My LinkedIn Profile</a> <br><br>
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" 
  data-theme="dark" data-type="VERTICAL" data-vanity="3liud" data-version="v1">
  <a class="badge-base__link LI-simple-link" href="https://ke.linkedin.com/in/3liud?trk=profile-badge">Eliud Nduati N</a></div>
              
  <a href="https://3liud.medium.com/">Check out my medium posts</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
